# Generated by Django 2.2 on 2021-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=11)),
            ],
        ),
    ]
