# Generated by Django 2.2 on 2021-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobby',
            field=models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('Movies', 'Movies'), ('Songs', 'Songs'), ('Football', 'Football')], max_length=20),
        ),
    ]
