# Generated by Django 2.2 on 2021-07-31 18:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hobby',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cricket', 'Cricket'), ('Movies', 'Movies'), ('Songs', 'Songs'), ('Football', 'Football')], max_length=29),
        ),
    ]
